error Exception message :) => 'name'

{
    "job_id": 2,
    "social_status": "single",
    "ar_r": 7,
    "ar_w": 7,
    "ar_s": 7,
    "ar_u": 7,
    "ar_o": 7,
    "en_r": 7,
    "en_w": 7,
    "en_s": 7,
    "en_u": 7,
    "en_o": 7,
    "full_name": "askdja",
    "surname": "lkasjflkdj",
    "email_from": "lkasjfdlk",
    "partner_phone": "lsakfjdlk",
    "address": "lkjaslkfja",
    "team_work": "excellent",
    "pressure": "excellent",
    "travel": "excellent",
    "referral_source": "walk-in"
}